### ISSUE TITLE
Failure installing since 4.0.2 release

### ISSUE THREAD

**Issue by jantman** [asmeurer/pytest-flakes#39]
Since the 4.0.2 release (within the last hour) I'm having installation failures.

The following is happening both in my TravisCI builds, as well as on my local Linux machine with Python 3.8.3 and pip 20.1.1:

```
$ pip install pytest-flakes==4.0.2
Collecting pytest-flakes==4.0.2
  Downloading pytest_flakes-4.0.2-py2.py3-none-any.whl (10 kB)
ERROR: pytest-flakes has an invalid wheel, multiple .dist-info directories found: pytest_flakes-4.0.1.dist-info, pytest_flakes-4.0.2.dist-info
```

**Comment by asmeurer** [comment]
Ah, I guess I messed up somehow. I yanked the release for now.

**Comment by jantman** [comment]
Ok, thanks. I wish I could help, but I've never seen that error before...

**Comment by asmeurer** [comment]
Here's the output from the command that I used to build the wheel

```
$python setup.py sdist bdist_wheel
running sdist
running egg_info
writing pytest_flakes.egg-info/PKG-INFO
writing dependency_links to pytest_flakes.egg-info/dependency_links.txt
writing entry points to pytest_flakes.egg-info/entry_points.txt
writing requirements to pytest_flakes.egg-info/requires.txt
writing top-level names to pytest_flakes.egg-info/top_level.txt
reading manifest file 'pytest_flakes.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pytest_flakes.egg-info/SOURCES.txt'
running check
warning: Check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too

creating pytest-flakes-4.0.2
creating pytest-flakes-4.0.2/pytest_flakes.egg-info
copying files to pytest-flakes-4.0.2...
copying LICENSE -> pytest-flakes-4.0.2
copying MANIFEST.in -> pytest-flakes-4.0.2
copying README.rst -> pytest-flakes-4.0.2
copying pytest_flakes.py -> pytest-flakes-4.0.2
copying setup.cfg -> pytest-flakes-4.0.2
copying setup.py -> pytest-flakes-4.0.2
copying test_flakes.py -> pytest-flakes-4.0.2
copying tox.ini -> pytest-flakes-4.0.2
copying pytest_flakes.egg-info/PKG-INFO -> pytest-flakes-4.0.2/pytest_flakes.egg-info
copying pytest_flakes.egg-info/SOURCES.txt -> pytest-flakes-4.0.2/pytest_flakes.egg-info
copying pytest_flakes.egg-info/dependency_links.txt -> pytest-flakes-4.0.2/pytest_flakes.egg-info
copying pytest_flakes.egg-info/entry_points.txt -> pytest-flakes-4.0.2/pytest_flakes.egg-info
copying pytest_flakes.egg-info/requires.txt -> pytest-flakes-4.0.2/pytest_flakes.egg-info
copying pytest_flakes.egg-info/top_level.txt -> pytest-flakes-4.0.2/pytest_flakes.egg-info
Writing pytest-flakes-4.0.2/setup.cfg
Creating tar archive
removing 'pytest-flakes-4.0.2' (and everything under it)
running bdist_wheel
running build
running build_py
copying pytest_flakes.py -> build/lib
installing to build/bdist.macosx-10.9-x86_64/wheel
running install
running install_lib
copying build/lib/pytest_flakes.py -> build/bdist.macosx-10.9-x86_64/wheel
running install_egg_info
Copying pytest_flakes.egg-info to build/bdist.macosx-10.9-x86_64/wheel/pytest_flakes-4.0.2-py3.7.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-10.9-x86_64/wheel/pytest_flakes-4.0.2.dist-info/WHEEL
creating 'dist/pytest_flakes-4.0.2-py2.py3-none-any.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
adding 'pytest_flakes.py'
adding 'pytest_flakes-4.0.1.dist-info/LICENSE'
adding 'pytest_flakes-4.0.1.dist-info/METADATA'
adding 'pytest_flakes-4.0.1.dist-info/WHEEL'
adding 'pytest_flakes-4.0.1.dist-info/entry_points.txt'
adding 'pytest_flakes-4.0.1.dist-info/top_level.txt'
adding 'pytest_flakes-4.0.2.dist-info/LICENSE'
adding 'pytest_flakes-4.0.2.dist-info/METADATA'
adding 'pytest_flakes-4.0.2.dist-info/WHEEL'
adding 'pytest_flakes-4.0.2.dist-info/entry_points.txt'
adding 'pytest_flakes-4.0.2.dist-info/top_level.txt'
adding 'pytest_flakes-4.0.2.dist-info/RECORD'
removing build/bdist.macosx-10.9-x86_64/wheel
```

It is including dist-info for 4.0.1, but I don't understand why.

**Comment by asmeurer** [comment]
It looks like it was also including the 4.0.2 wheel in the 4.0.1 release. I deleted it. Hopefully the install should be working now.

**Comment by jantman** [comment]
I've never yanked a package from PyPI before... the install is still failing for me, but even if I disable local cache (``pip --no-cache-dir install pytest-flakes``) it's still pulling 4.0.2. I can only assume that somewhere in the PyPI infrastructure, something hasn't expired yet after the yank...

**Comment by asmeurer** [comment]
Can you try again. I've deleted the 4.0.2 wheel from PyPI. I unyanked 4.0.2 with only the source install, which should work. I tested it and it seems to be working.

**Comment by asmeurer** [comment]
You may also have to use `--no-cache-dir` in your pip install if you already installed the 4.0.2 wheel previously.

**Comment by jantman** [comment]
That worked locally now, thanks so much!!!

**Comment by jantman** [comment]
Working in TravisCI as well, after deleting the build cache. Once again, thank you *so* much!

**Comment by asmeurer** [comment]
I'd like to figure out what I did wrong when creating the wheel. I can't reproduce the issue. Maybe there is a bug in the package tooling. I don't know why a wheel would even be allowed to have more than one version inside of it. If anyone has any guesses, please let me know. 

I guess I'll just need to check for this next time. I'm going to close this issue.
